// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDslyf-73CSQ6cv8ruKmEBS5axhuXl7pYs',
    appId: '1:318551257777:web:90b54e1be6cb4370b2e890',
    messagingSenderId: '318551257777',
    projectId: 'h-l-s-app',
    authDomain: 'h-l-s-app.firebaseapp.com',
    storageBucket: 'h-l-s-app.firebasestorage.app',
    measurementId: 'G-R9Z5XF1WTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4J7CnC20zWid1ack7i-P8y2BUTf0gQTo',
    appId: '1:318551257777:android:92b4d6a8b40766f6b2e890',
    messagingSenderId: '318551257777',
    projectId: 'h-l-s-app',
    storageBucket: 'h-l-s-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeZUU8bLTvus3OoOYeYfowX6nv4e6BRYY',
    appId: '1:318551257777:ios:14665e24f89bcd5bb2e890',
    messagingSenderId: '318551257777',
    projectId: 'h-l-s-app',
    storageBucket: 'h-l-s-app.firebasestorage.app',
    iosBundleId: 'com.example.hLSApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeZUU8bLTvus3OoOYeYfowX6nv4e6BRYY',
    appId: '1:318551257777:ios:14665e24f89bcd5bb2e890',
    messagingSenderId: '318551257777',
    projectId: 'h-l-s-app',
    storageBucket: 'h-l-s-app.firebasestorage.app',
    iosBundleId: 'com.example.hLSApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDslyf-73CSQ6cv8ruKmEBS5axhuXl7pYs',
    appId: '1:318551257777:web:42fb2ee2d0fcc8ceb2e890',
    messagingSenderId: '318551257777',
    projectId: 'h-l-s-app',
    authDomain: 'h-l-s-app.firebaseapp.com',
    storageBucket: 'h-l-s-app.firebasestorage.app',
    measurementId: 'G-8ET8FZJN1Z',
  );
}
